spring.application.name=BankManagementSystem

server.port=8081
server.address=127.0.0.1


spring.datasource.url=jdbc:mysql://localhost:3306/bankmanagementsystemapplication
spring.datasource.username=root
spring.datasource.password=manisha@24
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true









